import { cn } from "@/lib/utils";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <body
          className={cn(
            inter.className,
            "w-screen flex justify-center bg-slate-50"
          )}
        >
          <main className="h-full w-full max-w-md bg-white overflow-auto">
            {children}
          </main>
        </body>
      </html>
    </Providers>
  );
}
